# Generated by Django 4.0 on 2025-06-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_debitair_debit_air_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bendung',
            name='koordinat',
        ),
        migrations.AddField(
            model_name='bendung',
            name='koordinat_bt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bendung',
            name='koordinat_ls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
